using apiprojnew.Common;
using apiprojnew.Data;
using apiprojnew.Services.Users;
using apiprojnew.Services.Documents;
using apiprojnew.Services.News;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using System.Text;
using apiprojnew.Services.Admin;

Environment.SetEnvironmentVariable("DOTNET_USE_POLLING_FILE_WATCHER", "true");

var builder = WebApplication.CreateBuilder(new WebApplicationOptions
{
    Args = args
});

builder.Configuration.Sources.Clear();
builder.Configuration
    .AddJsonFile("appsettings.json", optional: false, reloadOnChange: false)
    .AddJsonFile($"appsettings.{builder.Environment.EnvironmentName}.json", optional: true, reloadOnChange: false)
    .AddEnvironmentVariables();

// Add services to the container.

builder.Services.AddControllers();

// Add CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy.SetIsOriginAllowed(origin => true)
              .AllowAnyMethod()
              .AllowAnyHeader()
              .AllowCredentials();
    });
});

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddSwaggerGen(option =>
{
    option.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme()
    {
        Name = "Authorization",
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer",
        BearerFormat = "JWT",
        In = ParameterLocation.Header,
        Description = "JWT Authorization header using the Bearer scheme. \r\n\r\n Enter 'Bearer' [space] and then your token in the text input below.\r\n\r\nExample: \"Bearer 1safsfsdfdfd\"",
    });

    option.AddSecurityRequirement(new OpenApiSecurityRequirement
{
     {
           new OpenApiSecurityScheme
             {
                 Reference = new OpenApiReference
                 {
                     Type = ReferenceType.SecurityScheme,
                     Id = "Bearer"
                 }
             },
             new string[] {}
     }
});
});

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = builder.Configuration["Jwt:Issuer"],
        ValidAudience = builder.Configuration["Jwt:Audience"],
        IssuerSigningKey = new SymmetricSecurityKey(
            Encoding.UTF8.GetBytes(builder.Configuration["Jwt:Key"]!))
    };
});

builder.Services.AddScoped<SmtpService>();
builder.Services.AddScoped<IAdminService, AdminService>();
builder.Services.AddScoped<IUserService, UserService>();
builder.Services.AddScoped<IDocumentService, DocumentService>();
builder.Services.AddScoped<INewsService, NewsService>();
builder.Services.AddSingleton<apiprojnew.Common.WebPushService>();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddDbContext<DataContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("Default")));

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<DataContext>();
    try
    {
        dbContext.Database.EnsureCreated();
        dbContext.Database.ExecuteSqlRaw(@"
            CREATE TABLE IF NOT EXISTS ""News"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""Title"" text NOT NULL,
                ""Text"" text NOT NULL,
                ""DateCreated"" timestamp with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
                CONSTRAINT ""PK_News"" PRIMARY KEY (""Id"")
            );
            ALTER TABLE ""News"" ADD COLUMN IF NOT EXISTS ""LinksJson"" text NULL;
            ALTER TABLE ""News"" ADD COLUMN IF NOT EXISTS ""TitleEn"" text NULL;
            ALTER TABLE ""News"" ADD COLUMN IF NOT EXISTS ""TextEn"" text NULL;
            CREATE TABLE IF NOT EXISTS ""NewsAttachments"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""NewsId"" integer NOT NULL,
                ""FileName"" text NOT NULL,
                ""StoredFileName"" text NOT NULL,
                ""FileSize"" bigint NOT NULL,
                ""ContentType"" text NOT NULL,
                ""UploadedAt"" timestamp with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
                CONSTRAINT ""PK_NewsAttachments"" PRIMARY KEY (""Id""),
                CONSTRAINT ""FK_NewsAttachments_News_NewsId"" FOREIGN KEY (""NewsId"") REFERENCES ""News"" (""Id"") ON DELETE CASCADE
            );
            CREATE TABLE IF NOT EXISTS ""PushSubscriptions"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""UserId"" integer NOT NULL,
                ""Endpoint"" text NOT NULL,
                ""P256dh"" text NOT NULL,
                ""Auth"" text NOT NULL,
                ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
                CONSTRAINT ""PK_PushSubscriptions"" PRIMARY KEY (""Id""),
                CONSTRAINT ""FK_PushSubscriptions_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
            );
        ");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"DB Auto Table Creation Exception: {ex.Message}");
    }
}

// Configure the HTTP request pipeline.
app.UseSwagger();
app.UseSwaggerUI();

// Comment out HTTPS redirection during HTTP local development to prevent 307 redirect CORS issues
// app.UseHttpsRedirection();

// Use CORS before authentication
app.UseCors("AllowFrontend");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();